return {
    { 'AlexvZyl/nordic.nvim',            lazy = false, priority = 1000 },
    { 'atelierbram/Base2Tone-nvim',      lazy = false, priority = 1000 },
    { 'catppuccin/nvim',                 lazy = false, priority = 1000 },
    { 'cocopon/iceberg.vim',             lazy = false, priority = 1000 },
    { 'deparr/tairiki.nvim',             lazy = false, priority = 1000 },
    { 'EdenEast/nightfox.nvim',          lazy = false, priority = 1000 },
    { 'ellisonleao/gruvbox.nvim',        lazy = false, priority = 1000 },
    { 'folke/tokyonight.nvim',           lazy = false, priority = 1000 },
    { 'gmr458/vscode_modern_theme.nvim', lazy = false, priority = 1000 },
    { 'jacoborus/tender.vim',            lazy = false, priority = 1000 },
    { 'kepano/flexoki-neovim',           lazy = false, priority = 1000 },
    { 'liuchengxu/space-vim-dark',       lazy = false, priority = 1000 },
    { 'loctvl842/monokai-pro.nvim',      lazy = false, priority = 1000 },
    { 'lunarvim/horizon.nvim',           lazy = false, priority = 1000 },
    { 'Mofiqul/vscode.nvim',             lazy = false, priority = 1000 },
    { 'neanias/everforest-nvim',         lazy = false, priority = 1000 },
    { 'NLKNguyen/papercolor-theme',      lazy = false, priority = 1000 },
    { 'olimorris/onedarkpro.nvim',       lazy = false, priority = 1000 },
    { 'patstockwell/vim-monokai-tasty',  lazy = false, priority = 1000 },
    { 'projekt0n/github-nvim-theme',     lazy = false, priority = 1000 },
    { 'rebelot/kanagawa.nvim',           lazy = false, priority = 1000 },
    { 'rose-pine/neovim',                lazy = false, priority = 1000 },
    { 'sainnhe/sonokai',                 lazy = false, priority = 1000 },
    { 'savq/melange-nvim',               lazy = false, priority = 1000 },
    { 'Shatur/neovim-ayu',               lazy = false, priority = 1000 },
    { 'lunacookies/vim-colors-xcode',    lazy = false, priority = 1000 },
}
